//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bd : DbContext
    {
        private static Bd _context;

        internal static Bd GetCintext()
        {
            if (_context == null)
                _context = new Bd();
            return _context;
        }

        public Bd()
            : base("name=Bd")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        /// <summary>
        /// 
        /// </summary>
        public virtual DbSet<Izgotoviteli> Izgotoviteli { get; set; }
       /// <summary>
       /// ewfwe
       /// </summary>
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual DbSet<Pokypateli> Pokypateli { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual DbSet<Sotrydniki> Sotrydniki { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual DbSet<Tovary> Tovary { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual DbSet<User> User { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual DbSet<Zakazy> Zakazy { get; set; }
    }
}
