//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izgotoviteli
    {
        public int Kod_izgotovitelya { get; set; }
        public string Nazv_izgotovitelya { get; set; }
        public string Adres { get; set; }
        public string Director { get; set; }
        public Nullable<decimal> Kod_zakaza { get; set; }
    }
}
