//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrydniki
    {
        public int Kod_sotrydnika { get; set; }
        public string FIO { get; set; }
        public string Adres { get; set; }
        public string Doljnost { get; set; }
        public Nullable<decimal> Zarplata { get; set; }
    }
}
