//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovary
    {
        public int Kod_tovara { get; set; }
        public string Nazvanie { get; set; }
        public Nullable<decimal> Kod_izgotovitelya { get; set; }
        public string Chena { get; set; }
        public string Sostoyanie { get; set; }
        public string Kategoria { get; set; }
        public string Kolichestvo { get; set; }
        public string Prihod { get; set; }
        public string Rashod { get; set; }
    }
}
