//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazy
    {
        public int Kod_zakaza { get; set; }
        public Nullable<decimal> Kolich_krasok { get; set; }
        public Nullable<System.DateTime> Sroki { get; set; }
        public string Postavshik { get; set; }
        public string Zakazchil { get; set; }
        public Nullable<decimal> Kod_sotrydnika { get; set; }
        public Nullable<decimal> Kod_tovara { get; set; }
        public Nullable<decimal> Kod_pokypatelya { get; set; }
    }
}
